FROM amazonlinux:2
RUN yum update -y
RUN yum install -y passwd sudo shadow-utils util-linux man vim lsof procps strace screen net-tools iproute
COPY Dockerfiles/systemctl.py /usr/bin/systemctl
RUN chmod a+x /usr/bin/systemctl
RUN adduser wiley
RUN echo 'wiley:password' | chpasswd
RUN passwd --expire wiley
RUN echo "wiley ALL=(ALL) ALL" >> /etc/sudoers
USER wiley
WORKDIR /home/wiley
