version: "3.9"

volumes:
  awslinux2-volume:
    driver: local
    driver_opts:
      type: none
      o: bind

services:
    awslinux2:
        build:
            context: .
            dockerfile: Dockerfiles/Dockerfile_awslinux2
        cap_add:
            - SYS_PTRACE
        volumes:
            - ./awslinux2-volume:/home/wiley/shared
        container_name: awslinux2-container
        tty: true
        ports:
            - "80:80"

